module.exports.luckyStone = {
    '1z': '🀀',
    '2z': '🀁',
    '3z': '🀂',
    '4z': '🀃',
    '5z': '🀆',
    '6z': '🀅',
    '7z': '🀄',
    '1m': '🀇',
    '2m': '🀈',
    '3m': '🀉',
    '4m': '🀊',
    '5m': '🀋',
    '6m': '🀌',
    '7m': '🀍',
    '8m': '🀎',
    '9m': '🀏',
    '1p': '🀙',
    '2p': '🀚',
    '3p': '🀛',
    '4p': '🀜',
    '5p': '🀝',
    '6p': '🀞',
    '7p': '🀟',
    '8p': '🀠',
    '9p': '🀡',
    '1s': '🀐',
    '2s': '🀑',
    '3s': '🀒',
    '4s': '🀓',
    '5s': '🀔',
    '6s': '🀕',
    '7s': '🀖',
    '8s': '🀗',
    '9s': '🀘',
};

module.exports.luckyKuji = {
    '7': '【大吉】Glückssträhne',
    '6': '【吉】Sehr Glücklich',
    '5': '【中吉】Glücklich',
    '4': '【小吉】Etwas Glücklich',
    '3': '【末吉】Wenig Glücklich',
    '2': '【平】Normal',
    '1': '【凶】Pech',
}

module.exports.luckyGrade = {
    '7': '★★★★★★★',
    '6': '★★★★★★☆',
    '5': '★★★★★☆☆',
    '4': '★★★★☆☆☆',
    '3': '★★★☆☆☆☆',
    '2': '★★☆☆☆☆☆',
    '1': '★☆☆☆☆☆☆',
}

module.exports.luckyYaku = {
    '0':'里ドラ Ura Dora',
    '1':'門清自摸 Menzen tsumo',
    '2':'立直 Riichi',
    '3':'一発 Ippatsu!',
    '4':'平和 Pinfu',
    '5':'一盃口 Iipeikou',
    '6': '役牌 Yakuhai',
    '7': '断幺九 Tanyao~',

    '8': '一気通貫 Ikkitsuukan',
    '9': '三色同順 Sanshoku doujun',
    '10': '対々和 Toitoi',
    '11': '混全帯幺九 Chanta',
    '12': '七対子 Chiitoitsu',
    '13': '純全帯么九 Junchan',
    '14': '混一色 Honitsu',

    '15': '清一色 Chinitsu',
    '16': '三暗刻 Sanankou',
    '17': '小三元 Shousangen',
    '18': '混老頭 Honroutou',
    '19': '二盃口 Ryanpeikou',
    '20': '三色同刻 SanshokuDoukou!',
    '21': '三槓子 Sankantsu !!?',
    '22': 'Dora dora dora!!',

    '23': '天和 Tenhou',
    '24': '地和 Chihou',
    '25': '大三元 Daisangen',
    '26': '四暗刻 Suuankou',
    '27': '四暗刻単騎 Suuankou TANKI',
    '28': '字一色 Tsuuiisou',
    '29': '緑一色 Ryuuuiisou',
    '30': '清老頭 Chinroutou',
    '31': '九蓮宝燈 Chuuren',
    '33': '国士無双 Kokushi',
    '34': '国士13面 Kokushi 13 men',
    '35': '大四喜 Daisuushii',
    '36': '小四喜 Shousuushii',
    '38': '人和 Ren-Renhou ?',
    '39': '流満 ~Nagashi mangan~?',
    '40': '~Kazoe~ Yakuman !?',
    '41': '役満 Yakuman',
    '42': '2倍役満 ~DOUBLE~ Yakuman',
    '43': '3倍役満 ~TRIPLE~ Yakuman',
    '32': '純正九蓮 Junsei Chuuren',
    '37': '四槓子 Suukantsu',
};

const luckySentence = {
        "0": "A sharp axe is easier to wield than a sharp wit",
        "1": "All roads lead to chaos, in the end",
        "2": "Always consider the consequences of yer deeds lest ye be surprised",
        "3": "Always watch your back!",
        "4": "An anvil is nothing more than an oversized ingot of iron",
        "5": "Being light as a feather makes you very rifty",
        "6": "Care for more intelligent monsters",
        "7": "Don't believe everything *they* say",
        "8": "Dragons want items made from their hide back",
        "9": "Eating a demon daisy will make you a demon lover",
        "10": "Gift shops are overpriced, unless you use a five finger discount",
        "11": "If you are doomed, this will be the last fortune you ever read",
        "12": "If you eat the heart of a Dragon, you will share in its strength",
        "13": "If you lick a Karmic Lizard, you can get high",
        "14": "In the land of eternal darkness, light must come from within",
        "15": "It takes an iron stomach to eat black dragon steak",
        "16": "Join DARK (*D*ragons *a*gainst *r*easonable *k*illing)",
        "17": "Living sacrifices are the most valuable of all",
        "18": "Look for strange items",
        "19": "MADE: Mindcrafters Against Drunken Explorers",
        "20": "Note: Don't forget to throw all the poisoned cookies away",
        "21": "Putting undead to rest with holy water indeed is a lawful act",
        "22": "Quidquid latine dictum sit, altum viditur",
        "23": "Remember to write something on this cookie",
        "24": "Rifts are deep",
        "25": "Scrolls of balance speak of rocks of alignment",
        "26": "Smoking is bad for your health!",
        "27": "Some gems harbor magical powers",
        "28": "Sting and Needle... Needle and Sting... twins they are and united they should be",
        "29": "Stoma Pubis enjoys throwing anvils at opponents",
        "30": "The coin of chaos has two faces- power and corruption",
        "31": "The Mad Minstrel harbors a dark secret",
        "32": "They say it is not wise to leave one's cause after being crowned to be a champion",
        "33": "They say that a good memory might pay",
        "34": "They say that a paragon of Order must not violate his beliefs by any means",
        "35": "They say that all white dragons suffer from a bad cold",
        "36": "They say that an empty stomach is one's worst enemy",
        "37": "They say that at times mindless rage might save your life in fights",
        "38": "They say that at times things can get zorky",
        "39": "They say that attacking shopkeepers is bad for your karma",
        "40": "They say that balors are the gatekeepers of Chaos",
        "41": "They say that being able to read is very useful when visiting the library",
        "42": "They say that Berzio potions are useful for taming monsters",
        "43": "They say that blessed items improve one's eyesight",
        "44": "They say that blessed potions of extra healing might be a real boon",
        "45": "They say that boozed bozos can be very helpful",
        "46": "They say that bugs can be really nasty",
        "47": "They say that burning torches can be very dangerous",
        "48": "They say that champions may pray for more favors than ordinary people",
        "49": "They say that companions fear darkness",
        "50": "They say that controlled teleportation is really great",
        "51": "They say that converting an altar is difficult without losing one's faith",
        "52": "They say that corpses mark the realm of death",
        "53": "They say that corrupted things can be your boon and your doom",
        "54": "They say that corruption harbors great might... and great weakness!",
        "55": "They say that cursed potions of invisibility might have strange effects",
        "56": "They say that cursed thieves picks might do strange things",
        "57": "They say that dark elves are especially good in the night",
        "58": "They say that distortion is the way to godhood",
        "59": "They say that dogs become more loyal when fed",
        "60": "They say that drinking black potions during the night corrupts your soul",
        "61": "They say that drinking holy water with bland rations will make them taste better",
        "62": "They say that eating beings of true evil corrupts your very essence",
        "63": "They say that eating humans is evil",
        "64": "They say that eating magic-wielding monsters might be a boon for your mana",
        "65": "They say that elemental altars can only be converted by the most faithful",
        "66": "They say that elves trade strength of body for speed",
        "67": "They say that every coin has two sides",
        "68": "They say that excitement is a messenger of battle",
        "69": "They say that faster blood means faster recovery",
        "70": "They say that feeding rust monsters is costly but definitely worth it",
        "71": "They say that fire is the most violent element. Be as resistant as you can",
        "72": "They say that Fire is the only element living on the surface",
        "73": "They say that fortunes must be followed by the incantation 'in bed' to work",
        "74": "They say that fury makes you less stubborn",
        "75": "They say that gods like sacrifices of food and valuable stuff",
        "76": "They say that good gamblers know which coins they have to use",
        "77": "They say that gambling is bad for your finances",
        "78": "They say that graveyards are dangerous places",
        "79": "They say that greater vaults are hiding places for artifacts",
        "80": "They say that green pools contain deadly slime",
        "81": "They say that herb bushes grow according to magical patterns",
        "82": "They say that herbs have strange effects",
        "83": "They say that holy water might bear fruits",
        "84": "They say that hurthlings don't like shoes",
        "85": "They say that Infinity does not permit to visit any place twice",
        "86": "They say that it is good for your survival if you can't hear death coming",
        "87": "They say that it might be useful to remain persistent with uncharged wands",
        "88": "They say that it might come in handy to discover a use for useless potions",
        "89": "They say that Khelavaster is still alive",
        "90": "They say that kicking a stuck door helps",
        "91": "They say that kicking stairs helps to train your strength",
        "92": "They say that kicking stairs might be bad for your health",
        "93": "They say that killing cats is bad for your karma",
        "94": "They say that killing friends won't help you finding new ones",
        "95": "They say that libraries are especially useful for wizards",
        "96": "They say that long jumps require small moves",
        "97": "They say that Mana is a kind of side trek",
        "98": "They say that many cursed items cause bad luck",
        "99": "They say that many wands depend on the power of their wielder",
        "100": "They say that merchants are really well-spoken thieves",
        "101": "They say that merchants are well-versed in handling coins",
        "102": "They say that monsters tamed by bards will never willingly leave",
        "103": "They say that monuments can hold dark secrets",
        "104": "They say that nobody ever heard the wail of the Banshee more than once",
        "105": "They say that not all herbs must be eaten",
        "106": "They say that once you have opened the final gate there is no way back",
        "107": "They say that patience is the better part of valor",
        "108": "They say that pools contain mysterious secrets",
        "109": "They say that potions of booze and mana-rich potions are able to charge more than just your alcohol level",
        "110": "They say that potions of toughness tend to remove your hungry feelings",
        "111": "They say that praying at altars of your deity is helpful",
        "112": "They say that quests are noble and just",
        "113": "They say that repetitive requests are frowned upon by the gods",
        "114": "They say that rubbing moss of mareilon onto your skin might get you moving",
        "115": "They say that rusted electrical items might be dangerous to the user",
        "116": "They say that sacrifices can be dangerous",
        "117": "They say that shopkeepers base their prices upon racial preference",
        "118": "They say that shopkeepers sometimes try to cheat the customer",
        "119": "They say that shops are dangerous at night",
        "120": "They say that Sis might enhance your creativity",
        "121": "They say that skeletons like bones",
        "122": "They say that some items are especially deadly in combat...no matter how you use them.",
        "123": "They say that some items are useful when worn shortly before special moments",
        "124": "They say that smashing statues might wield magical wands",
        "125": "They say that some statues have magical bones",
        "126": "They say that some stuff needs a lot of blessing to improve",
        "127": "They say that some wands are not very reliable",
        "128": "They say that swamp hydras are tough food",
        "129": "They say that the ancient dwarf knows a lot about quests",
        "130": "They say that the banshee transformed after losing her beloved husband",
        "131": "They say that the cat lord finds no fault with ye if ye never harmed any cat",
        "132": "They say that the dungeons of mystery consist of 100 levels",
            "133": "They say that the ancient dwarf knows a lot about quests",
            "134": "They say that the banshee transformed after losing her beloved husband",
            "135": "They say that the cat lord finds no fault with ye if ye never harmed any cat",
            "136": "They say that the dungeons of mystery consist of 100 levels",
            "137": "They say that the essence of mareilon moss is proof against the undead",
            "138": "They say that the forces of Law built a monument to Infinity",
            "139": "They say that the gods do not yearn for material wealth",
            "140": "They say that the gods greatly favor living sacrifices",
            "141": "They say that the great rift is very dangerous for almost anyone",
            "142": "They say that the guild of industrious brutal muggers writes really confusing manuals",
            "143": "They say that the home of the banshee is ruled by eternal decay",
            "144": "They say that the king hid a lot of gold in these dungeons",
            "145": "They say that the library charges high fees",
            "146": "They say that the lofty nature of some writing sets is influenced by the degree of magic invoked with it",
            "147": "They say that the mint-flavoured juice distilled out of morgia roots improves Toughness, slakes thirst and conceals bad breath",
            "148": "They say that the radiance of chaos will corrupt you faster the deeper you descend",
            "149": "They say that the secret to becoming a Chaos God is hidden in the Drakalor Chain",
            "150": "They say that there are many gems deep under the mountains",
            "151": "They say that there is a secret level guarded by many powerful monsters which contains several artifacts",
            "152": "They say that thick gauntlets are great for isolating your hands",
            "153": "They say that those who have too many friends also have too many enemies",
            "154": "They say that those who hear the wail of the banshee are doomed",
            "155": "They say that those who manage to empty a pool will receive a wish",
            "156": "They say that tiny caves can be very large",
            "157": "They say that to be a champion of one's cause is very valuable when using ancient magic",
            "158": "They say that too much chaos essence corrupts thy inner self",
            "159": "They say that true berserkers fight naked",
            "160": "They say that using artifacts costs a lot of energy",
            "161": "They say that wands of knocking might split your skull",
            "162": "They say that when you hear a \"Hurumph!\" you'd better start to run",
            "163": "They say that you might find gems in the deep levels",
            "164": "They say that you need a lot of leverage to stop the forces of Chaos",
            "165": "They say that you need a strong will to enter the great rift",
            "166": "They say that you need persistence and peace to truly profit from religious scriptures",
            "167": "They say that you need to be an expert climber to survive the great rift",
            "168": "They say that you need to be very experienced to enter the great rift",
            "169": "They say that you only can be the champion of your deity if you are very close to your deity",
            "170": "They say that you should not slow down in your final fight",
            "171": "They say that you should seek the heart of the mountains",
            "172": "They say that you should try to investigate the potential uses of beewax",
            "173": "They say that you should wish for appearance",
            "174": "They say that you should wish for charisma",
            "175": "They say that you should wish for dexterity",
            "176": "They say that you should wish for friends",
            "177": "They say that you should wish for knowledge",
            "178": "They say that you should wish for mana",
            "179": "They say that you should wish for strength",
            "180": "They say that you should wish for toughness",
            "181": "They say that you should wish for wealth",
            "182": "They say that you should wish for willpower",
            "183": "They say that you should wish for wishes",
            "184": "They say that you will feel the corrupting incursions of Chaos",
            "185": "They say that you will need a weapon of mass destruction to come closer to your goal",
            "186": "They say that you'll have to pull mightily to plug the chaotic intrusions",
            "187": "They say that your piety depends on your disposition towards all gods of your pantheon",
            "188": "They say ye cannot shoot yourself, no matter how hard ye try",
            "189": "This cookie will make you pay a high price",
            "190": "This is a joke",
            "191": "Those of Trollish Blood must drink from the Bloody Pool",
            "192": "Those who guard artifacts are deadly enemies",
            "193": "Those without overwhelming piety won't affect elemental altars",
            "194": "To be heavy in not very nifty in a deep rift",
            "195": "To leave the Animated Forest you will have to reach the corner opposite the entrance",
            "196": "Who are they, anyway?",
            "197": "Ye dost not need to find some kind of amulet to save the world",
            "198": "Your termination is long due",
            "199": "They say that Rolf was left-handed.",
            "200": "They say that Rolf was killed and an impostor has taken his place millenia ago!",
            "201": "They say Rolf built an abomination from the most powerful artifact of dwarvenkind and now is trying to cover it up",
            "202": "They say that Rolf was an agent of Chaos with a particularly vile plan to consume the world!",
            "203": "They say that Rolf is guilty of murdering his own blood and he tried to cover it up.",
            "204": "They say that Rolf is nothing but a legend.",
            "205": "They say that sometimes it needs a heavy hit to transmogrify horror into something useful.",
            "206": "They say that the merchants guild welcomes lucky adventurers.",
            "207": "They say that lucky people can find access to great wealth in the south-eastern Drakalor Chain... if they search hard enough.",
            "208": "They say that not all is at it seems.",
            "209": "They say that some fires take great efforts to spark!",
            "210": "Staves must be held to unlock their full potential",
            "211": "To change the gods of chaos would require nothing less than the end of the world.",
            "212": "They say that the gods of chaos are the only ones who can save the world.",
            "213": "They say that a single stone can be used to unpick reality and create strong new ties!",
            "214": "They say that a legendary knight called Michal once led an army of stone skeletons against the forces of Chaos.",
};

module.exports.luckySentence = [
    "With integrity and consistency -- your credits are piling up.",
    "Reach out your hand today to support others who need you.",
    "It is not the outside riches bit the inside ones that produce happiness.",
    "How dark is dark?, How wise is wise?",
    "We can admire all we see, but we can only pick one.",
    "The man who has no imagination has no wings.",
    "To courageously shoulder the responsibility of one's mistake is character.",
    "We can't help everyone. But everyone can help someone.",
    "You discover treasures where others see nothing unusual.",
    "Make all you can, save all you can, give all you can.",
    "Understanding the nature of change, changes the nature.",
    "You will be unusually successful in business.",
    "Your spirit of adventure leads you down an exiting new path.",
    "Genius is one percent inspiration and ninety-nine percent perspiration.",
    "You are the master of every situation.",
    "Be brave enough to live creatively.",
    "Cookies go stake. Fortunes are forever.",
    "Your ingenuity and imagination will get results.",
    "Unnecessary possessions are unnecessary burdens.",
    "Ability is not something to be shown off.",
    "If you wish to see the best in others, show the best of yourself.",
    "Your power is in your ability to decide.",
    "Wherever you go, whenever you can, try to leave a gift.",
    "Kind words can be shot and easy to speak, but their echoes are truly endless.",
    "Your ingenuity and imagination will get results.",
    "Age can never hope to with you while your heart is young.",
    "Example is better than perception.",
    "Idleness is the holiday of fools.",
    "Don't be pushed by your problems. Be led by your dreams.",
    "Many receive advice, only the wise profit from it.",
    "You will have good luck and overcome many hardships.",
    "A good way to keep healthy is to eat more Chinese food.",
    "Today's profits are yesterday's good well ripened.",
    "LSDBS - Let Something Good Be Said.",
    "There is in the worst of fortunes the best change of a happy ending.",
    "Service to many leads to greatness.",
    "Desire, like the atom, is explosive with creative force.",
    "I think and that is all that I am.",
    "Judge each day not by the harvest you reap but by the seeds you plant.",
    "Yesterday was a dare to struggle. Today is a dare to win.",
    "Make everyday your best. You will improve yourself greatly.",
    "You must be willing to act today in order to succeed.",
    "Venture not all in one boat.",
    "Suppressing a moment of anger may save a day of sorrow.",
    "Never be less than your dreams.",
    "The good times start when I count to 3: 1... 2... 3.",
    "An inch of time is an inch of gold.",
    "If you chase two rabbits both will escape.",
    "You will soon be surrounded by good friends and laughter.",
    "Haste does not bring success.",
    "You will stumble into the path that will lead your life to happiness.",
    "You will always be successful in you professional career.",
    "Good news will come to you from far away.",
    "Service is the rent you pay for having room on the Earth.",
    "Be smart, but never show it.",
    "The only certainty is that nothing is certain.",
    "You or a close friend will be married soon.",
    "We will not know the worth of water 'till the well is dry.",
    "You are talented in many ways.",
    "Do your best to make it happen",
    "You will find great forces in unexpected places.",
    "What you see in the mirror, and what you are can be two different images.",
    "Excuses are easy to manufacture, and hard to sell.",
    "Do onto others as you wish others do onto you.",
    "Struggle as and hard as you can for whatever you believe in.",
    "You have a pair of shining eyes.",
    "You should be able to undertake and complete anything.",
    "Your principles mean more to you than any money or success.",
    "Forgiveness does not change the past, but it does enlarge the future.",
    "Stand tall! Don't look down upon yourself.",
    "Every truly great accomplishment is at first impossible.",
    "Courage is not the absence of fear; it is the conquest of it.",
    "Wise man seldom talks.",
    "If you have a job without aggravations, you don't have a job.",
    "You are broad minded and socially active.",
    "Don't put off till tomorrow what can be enjoyed today.",
    "A family reunion in the coming months will be a tremendous success!",
    "Enthusiastic leadership gets you a promotion when you least expect it.",
    "Calamity is the touchstone of a brave mind.",
    "Everything you add to the truth subtracts from the truth.",
    "You are going to take a vacation.",
    "Commitment is the stuff character is made of; the power to change the face of things.",
    "A friend asks only for your time not your money.",
    "A friend asks only for your time not your money.",
    "A handful of patience is worth more than a bushel of brains.",
    "A handful of patience is worth more than a bushel of brains.",
    "To be eighty years young is more cheerful and hopeful than forty years old.",
    "To be eighty years young is more cheerful and hopeful than forty years old.",
    "A person is not wise simply because one talks a lot.",
    "It takes guts to get out of the ruts.",
    "The greatest quality is seeking to serve others.",
    "Most people, once they graduate from the school of Hard Knocks, automatically enroll.",
    "Everyone needs to be loved, especially those do not deserve it.",
    "Winning isn't everything but the will to win is.",
    "You display the wonderful traits of charm and courtesy.",
    "You will be awarded some great honor.",
    "Don't build your happiness on other's sorrow.",
    "The best thing about growing older is that it takes such a long time.",
    "You have a deep interest in all that is artistic.",
    "Kiss is not a kiss without the heart.",
    "Don't be afraid of fear.",
    "There's no point to being grown up if you can't be childish sometimes.",
    "You will learn something new every day.",
    "You can't go far in a rowboat without oars.",
    "Failure is the virtual way to prepare you for great responsibilities.",
    "Many receive advice only the wise profit by it.",
    "A banker is someone who lends you an umbrella when the sun is shining.",
    "Maturity: Do your duty without being supervised.",
    "Your cheerful outlook is one of your assets.",
    "You can't have everything... where would you put it all?",
    "You have an unusually magnetic personality.",
    "You have an unusually magnetic personality.",
    "He who hurries cannot walk with dignity.",
    "You never hesitate to tackle the most difficult problems.",
    "Your emotional nature is strong and sensitive.",
    "Serious trouble will bypass you.",
    "If you're riding ahead of the heard, look back once in a while to make sure it's still there.",
    "You have an iron will, which helps you succeed in everything.",
    "Three can keep a secret if you get rid of two.",
    "Everywhere you choose to go friendly faces will greet you.",
    "Nothing gets in the way of your vision of yourself in the future.",
    "To understand is hard. Once one understands, action is easy.",
    "The philosophy of one century is the common sense of the next.",
    "You will make many changes before settling satisfactorily.",
    "When in anger, sing the alphabet.",
    "Wealth is a means to an end... not the end itself.",
    "It's high time for one of your most promising ideas.",
    "Small opportunities are often the beginning of great enterprises.",
    "People are drawn to you and look to you for advice.",
    "Keep your feet on the ground even though friends flatter you.",
    "Do a good deed anonymously. You will make a difference in your life.",
    "Financial prosperity is coming your way!",
    "A healthy body will benefit you forever.",
    "Mental activity keeps you busy at this time.",
    "Say \"I love you\" and mean it. You can't do that enough.",
    "The world is always ready to receive talent with open arms.",
    "Enjoy the small things you find on your path.",
    "Good food brings good health and longevity.",
    "The act of giving is more important than receiving.",
    "Every burden is a blessing.",
    "Prosperity is in your fortune.",
    "Your next interview will result in a job.",
    "Accept the challenges, so that you may feel the exhilaration of victory.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Peace begins with a smile.",
    "Engage in group activities that further transformation.",
    "Be satisfied with what you already own.",
    "Your business will assume vast proportions.",
    "You have a potential urge and the ability for accomplishment.",
    "People find it difficult to resist your persuasive manner.",
    "Action is worry's worst enemy.",
    "Men do not fail... they give up trying.",
    "Are your legs tired? You been running through someone's mind ALL day long.",
    "You find beauty in ordinary things. Do not loose this ability.",
    "Will you let compassion to manage your wishes.",
    "A truly great person never puts away the simplicity of a child.",
    "Home is where your heart is.",
    "A huge fortune at home is not as good as money in use.",
    "Humor is the affirmation of dignity.",
    "Your heavy desire, only allow you to see what you are looking for.",
    "TEAMS - Together Everyone Achieves More Success.",
    "You have a heart of gold.",
    "Life to you is a bold and dashing responsibility.",
    "Want to learn how to love, start with the one you hate.",
    "There is beauty in simplicity.",
    "Learning is a treasure which accompanies us everywhere.",
    "It is much easier to be critical than to be correct.",
    "This person's love is just and true. You may rely on it.",
    "You will be spending time outdoors, in the mountains, near water.",
    "Friends long absent are coming back to you.",
    "He joyfulness of a man prolongeth his days.",
    "Regenerate your system through diet and exercise. Save the cookies!",
    "Listen to the wisdom of the old.",
    "Even the toughest of days have bright spots, just do your best.",
    "Your talents will be recognized and suitably rewarded.",
    "Fortitude is the guard and support of the other virtues.",
    "When the moment comes, take the one from the right.",
    "Old friends make best friends.",
    "You have an ability to sense and know higher truth.",
    "People learn little from success, but much from failure.",
    "Keep in mind your most cherished dreams of the future.",
    "You always do things the right way.",
    "Act boldly and unseen forces will come to your aid.",
    "Join a new club today, you'll be surprised.",
    "Your many hidden talents will become obvious to those around you.",
    "Some people never have anything except ideas, Go do it.",
    "A real patriot is the fellow who gets a parking ticket and rejoices that the system works.",
    "You are more likely to give than give in.",
    "If you bite the hand that feeds you, it wont taste as good as the food you were fed.",
    "The heart has its reasons, which the reasons dos not know.",
    "Even the longest of days will come to an end.",
    "You enjoy giving gifts of yourself to others, you will be rewarded!",
    "There are no stupid questions, just stupid answer.",
    "Success is an accumulation of successful days.",
    "You have a friendly heart and are well admired.",
    "Just because you put tap shoes on an elephant does not mean it can dance.",
    "Start to look for you faults if you never made mistakes.",
    "Good sense is the master of human life.",
    "Your luck has been completely changed today.",
    "Ask advice, but use your own common sense.",
    "A judgment will rule in your favor.",
    "Your winsome smile will be your sure protection.",
    "Go confidently in the direction of your dreams.",
    "The skills you have gathered will one day come in handy.",
    "Look forward to great fortune and a new lease on life!",
    "You will travel to many places.",
    "You will enjoy a trip to Asia.",
    "Better to do something imperfectly than to do nothing perfectly.",
    "Pure logic is the ruin of the spirit.",
    "You will have a long and wealthy life.",
    "Your smile always brightens the cloudiest days.",
    "A friend in the market is better than money in the purse.",
    "A new venture will be a success.",
    "It is by those who have suffered that the world is most advanced.",
    "Everything must have a beginning.",
    "The important thing is to express yourself.",
    "The real meaning of enlightenment is to gaze with undimmed eyes on all undimmed.",
    "New and rewarding opportunities will soon develop for you.",
    "Seek to assert your devotion when a worthy situation arises.",
    "The glass is not half-empty, it's just twice too big.",
    "A feeling is an idea with roots.",
    "Your present plans are going to succeed.",
    "A sound mind and healthy body bring many happy events to your family.",
    "Plan your work and work your plan.",
    "Courage is rightly considered the foremost of the virtues, for upon it, all others depend.",
    "Say hello to others. You will have a happier day.",
    "Don't let your limitations overshadow your talents.",
    "Love is the affinity which links and draws together the elements of the world.",
    "You should be able to undertake and complete anything.",
    "Character development is the true aim  of education.",
    "Trust him, but sill keep your eyes open.",
    "He who is shipwrecked the second time cannot lay the blame on Neptune.",
    "To get respect from others, one must first give respect to others.",
    "Walk the words you talk and talk the words you walk.",
    "People forget how fast you did a job - but they remember how well you did it.",
    "The time is right to make new friends.",
    "Do what is right, not what you should.",
    "Punctuality is the politeness of kings and the duty of gentle people everywhere.",
    "If you wait too long for the perfect moment, the perfect moment will pass you by.",
    "Your heart is pure, and your mind clear, and soul devout.",
    "Walk with a good heart and you will run with success.",
    "We should not let our fears hold us back from pursuing our hopes.",
    "Do not mistake temptation for opportunity.",
    "You will soon meet the person you admire.",
    "A good time to start something new.",
    "All generalities are false.",
    "Come back later... I am sleeping. (yes, cookies need their sleep too)",
    "If at first you do not succeed... try something harder.",
    "Your good listening skills will open many doors.",
    "Two people shorten a road.",
    "Stop waiting! Buy that ticket take that special trip!",
    "A problem clearly stated is a problem half solved.",
    "Accept your independence and use it wisely.",
    "May the warm winds of heaven blow softly upon your sprint."
  ]
          
      

